import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import NavDrawer from "@/components/shared/NavDrawer";
import { MobileNav } from "@/components/shared/MobileNav";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex">
        <MobileNav />
        <NavDrawer />
        <main className="flex-1 p-5 md:p-10 md:pl-26 lg:p-15 lg:pl-31 bg-slate-50/50">
          {children}
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
